{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Release.Namespace }} 
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: eso-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
  data:
  {{- range .Values.externalSecret.secrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef }}
  {{- end }}
{{- end }}
